Feature#15 code refactoring
BC-MAY-21-RN/kata-05-reservacion-de-vuelos-m22-k05-t2-reactive-02 pull request #33
Opened 2022-06-28 05:03 UTC by daniel-yocupicio

# Description
All code was refactored to eliminate codeclimate issues, some components were modified so that they do not exceed 25 lines and adapted so that the firebase clientid is not directly in the code.
   
  ## Screenshots 
test with jest, you already had a previous test but it was adapted to work with the refactored code. 
![image](https://user-images.githubusercontent.com/55728824/176095749-a7b0e7bf-addd-4077-a845-ac9cc9c3ca35.png)

Some screenshots of the views that the app has:
Sign Up.
![image](https://user-images.githubusercontent.com/55728824/176096295-093b9e39-a633-4357-8d56-2d78984de8b6.png)

Log in
![image](https://user-images.githubusercontent.com/55728824/176096383-c3d247f8-16b9-4b92-9a0b-d397a403c44a.png)

Flight list
![image](https://user-images.githubusercontent.com/55728824/176096444-ef12bac4-5130-4180-829c-c559a632b701.png)

Add Flight
![image](https://user-images.githubusercontent.com/55728824/176096537-7dc2d0b7-cfed-4541-aed7-872f133036d1.png)
![image](https://user-images.githubusercontent.com/55728824/176096578-9695ab43-2344-4937-88f5-9dd19f2da6eb.png)
![image](https://user-images.githubusercontent.com/55728824/176096621-2cf1a813-ed6d-4452-8c8f-89f48c0d72bf.png)
![image](https://user-images.githubusercontent.com/55728824/176096647-bdd550a2-eeee-475c-a0ba-736fa07ce3ab.png)
![image](https://user-images.githubusercontent.com/55728824/176096672-620ef86b-054e-4b76-ab2a-1c997b6be742.png)

A flight was added
![image](https://user-images.githubusercontent.com/55728824/176096758-b4781875-edea-491b-8c62-a7dc0a2edf0c.png)

2022-06-28 06:17 UTC, ShamuXX approved these changes, later dismissed

2022-06-28 06:17 UTC, LizyMiGo approved these changes, later dismissed

2022-06-28 18:23 UTC, YilKanda requested changes

2022-06-28 18:23 UTC, YilKanda commented on ReservacionDeVuelos/.env
> +CLIENT_ID=959127818437-tk3msn40d4lslgkrm57a8dp4sti7fl8l.apps.googleusercontent.com
This file should not appear on GitHUb, instead put an .env.example file.

2022-06-28 18:23 UTC, YilKanda commented on ReservacionDeVuelos/src/components/molecules/CardFlight.js
>        <FlightDetails fecha={fecha} passengers={passengers} />
Do not leave on GitHub in comments. If you don't use it, remove it.

2022-06-28 18:23 UTC, YilKanda commented on ReservacionDeVuelos/src/consts/globalstyles.js
> +*/
Do not leave on GitHub in comments. If you don't use it, remove it.

2022-06-28 20:10 UTC, YilKanda requested changes

2022-06-28 20:10 UTC, YilKanda commented on ReservacionDeVuelos/.gitignore
> +.env
Only you need to do is place the .env.example file

2022-06-28 20:12 UTC, ShamuXX approved these changes, later dismissed

2022-06-29 01:34 UTC, YilKanda approved these changes
LGTM!

2022-07-04 22:13 UTC, LizyMiGo approved these changes

2022-07-04 22:14 UTC, ShamuXX approved these changes

2022-07-04 22:15 UTC, LizyMiGo approved these changes

2022-07-04 22:15 UTC, merged